<a href="https://colab.research.google.com/github/zzaeyun/ESAA22-2/blob/main/100_Numpy_exercises_26to39.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [4]:
Z1= np.random.randint(0,10,10)
Z2= np.random.randint(0,10,10)

print(Z1, Z2, np.intersect1d(Z1,Z2))

[1 2 8 4 6 6 5 1 5 6] [1 5 0 4 1 2 2 3 8 6] [1 2 4 5 6 8]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [5]:
np.sqrt(-1) == np.emath.sqrt(-1)

#False

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

In [ ]:
import numpy as np

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [8]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [17]:
#신기한 방법

A = np.ones(3)
B = np.ones(3)*2

np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
print(np.multiply(A,B))

[-1.5 -1.5 -1.5]


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [20]:
Z=np.random.uniform(0,10,5)

print(Z%1)
print(Z-Z//1)

[0.93536348 0.67977682 0.38935206 0.07993057 0.01579743]
[0.93536348 0.67977682 0.38935206 0.07993057 0.01579743]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [24]:
Z=np.zeros((5,5))
Z+=np.arange(0,5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [27]:
#tile 함수, 신기한 방법
Z=np.tile(np.arange(0,5), (5,1))
print(Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [34]:
Z=np.random.random(size=10)
Z.sort()
print(Z)

[0.02041404 0.10320698 0.21940207 0.22926683 0.29111751 0.4036747
 0.46031029 0.5996469  0.67494399 0.98623689]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [35]:
A=np.random.randint(0,2,5)
B=np.random.randint(0,2,5)

np.array_equal(A,B)

False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [37]:
X=np.random.random(1)
Y=np.random.random(1)

r=np.sqrt(X**2+Y**2)
theta=np.arctan2(Y,X)

print(X,Y)
print(r,theta)

[0.00575244] [0.62386733]
[0.62389385] [1.56157597]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [38]:
Z=np.random.random(10)
Z[Z.argmax()]=0

print(Z)

[0.86774721 0.94820162 0.24746918 0.62701194 0.79108423 0.79963584
 0.15227142 0.34378502 0.         0.63550497]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [48]:
Z = np.arange(100)
v = np.random.uniform(0,100)
print(Z)
print(Z-v)
print(((Z-v)**2).argmin())
Z[((Z-v)**2).argmin()]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[-59.36039571 -58.36039571 -57.36039571 -56.36039571 -55.36039571
 -54.36039571 -53.36039571 -52.36039571 -51.36039571 -50.36039571
 -49.36039571 -48.36039571 -47.36039571 -46.36039571 -45.36039571
 -44.36039571 -43.36039571 -42.36039571 -41.36039571 -40.36039571
 -39.36039571 -38.36039571 -37.36039571 -36.36039571 -35.36039571
 -34.36039571 -33.36039571 -32.36039571 -31.36039571 -30.36039571
 -29.36039571 -28.36039571 -27.36039571 -26.36039571 -25.36039571
 -24.36039571 -23.36039571 -22.36039571 -21.36039571 -20.36039571
 -19.36039571 -18.36039571 -17.36039571 -16.36039571 -15.36039571
 -14.36039571 -13.36039571 -12.36039571 -11.36039571 -10.36039571
  -9.36039571  -8.36039571  -7.360

59

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [57]:
Z=np.arange(9).reshape(3,3)

#ndenumerate와 ndindex가 어떤 값을 반환하는지 어려움
print(np.ndenumerate(Z))
print(np.ndindex(Z.shape))

for (index, value) in np.ndenumerate(Z):
  print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [59]:
n = 10
p = 9
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),11)
print(Z)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 11.]
 [ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 11.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]
 [11.  0. 11.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 11.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 11.  0.  0.  0.  0.  0. 11.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [62]:
# column 1
# column1을 sort하는 순서대로 index값을 얻고 그걸로 print

Z=np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,0].argsort()])

[[3 1 8]
 [1 1 6]
 [8 7 2]]
[[1 1 6]
 [3 1 8]
 [8 7 2]]


In [63]:
# column 2
print(Z[Z[:,1].argsort()])

[[3 1 8]
 [1 1 6]
 [8 7 2]]


In [64]:
# column 3
print(Z[Z[:,2].argsort()])

[[8 7 2]
 [1 1 6]
 [3 1 8]]
