<a href="https://colab.research.google.com/github/zzaeyun/ESAA22-2/blob/main/%ED%8C%8C%EC%9D%B4%EC%8D%AC%EC%99%84%EB%B2%BD%EA%B0%80%EC%9D%B4%EB%93%9C_1to38.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **01 머신러닝의 개념**

---

**머신러닝이란?**
- 애플리케이션을 수정하지 않고도 데이터를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘 기법
- 수시로 변화하는 정보에 맞춰서 기존 로직을 수정하고 검증하는 프로세스에는 많은 비용과 시간이 요구되기 때문에 일정한 패턴을 찾기 어려운 경우 머신러닝이 훌륭한 솔루션
- 데이터 내의 패턴을 스스로 인지하고 신뢰도 있는 예측 결과를 도출

**머신러닝의 분류**
1. 지도학습 - 분류, 회귀, 추천 시스템, 시각/음성 감지/인지, 텍스트 분석, NLP
2. 비지도학습 - 클러스터링, 차원 축소, 강화 학습
3. 강화학습

**데이터 전쟁**

머신러닝의 중요한 요소: 데이터, 머신러닝 알고리즘

좋은 품질의 데이터를 갖추지 못한다면 머시러닝의 수행 결과도 좋을 수 없음 → 데이터에 의존적

데이터를 이해하고 효율적으로 가공, 처리, 추출해 최적의 데이터를 기반으로 알고리즘을 구동할 수 있도록 준비하는 능력이 중요

**파이썬과 R 기반의 머신러닝 비교**

R: 통계 전용 프로그램
파이썬: 다양한 영역에서 사용되는 개발 전문 프로그램 언어 → 직관적인 문법, 객체지향, 유연한 프로그램 아키텍처, 다양한 라이브러리
: 딥러닝에 대한 관심이 증가하며 파이썬에 대한 관심도 급격히 증가

*파이썬은 소리없이 프로그래밍 세계를 점령하고 있는 언어*
- 전 세계 개발자들이 파이썬을 선호, 높은 활용도
- 많은 라이브러리로 높은 생산성 보장
- 뛰어난 확장성, 유연성, 호환성
- 머신러닝 애플리케이션과 다양한 애플리케이션 개발 가능
- 다양한 기업 환경으로의 확산 가능

앞으로 딥러닝 프레임워크는 파이썬 중심으로 발전될 가능성이 있음




## **02 파이썬 머신러닝 생태계를 구성하는 주요 패키지**



---

머신러닝 패키지: 사이킷런(Scikit-Learn)

행렬/선형대수/통계 패키지: 넘파이(NumPy)

데이터 핸들링: 판다스, 맷플롯립(Matplotlib)

시각화: 맷플롯립 (+시본)

아이파이썬(주피터 노트북): 대화형 파이썬, 중요 코드 단위로 설명을 적고 코드를 수행해 그 결과를 볼 수 있게 하여 직관적으로 어떤 코드가 어떤 역할을 하는지 쉬운 이해 가능



## **03 넘파이**

---



- 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원

- 빠른 배열 연산속도 보장

- 호환 API 제공

- 다양한 데이터 핸들링 기능 제공

**넘파이 ndarray 개요**


In [1]:
import numpy as np

array(): 리스트와 같은 인자를 입력 받아서 ndarray로 변환
- shape: ndarray의 크기, 행과 열의 수를 튜플 형태로 가지고 있음

In [3]:
array1=np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2=np.array([[1,2,3],
                [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3=np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


ndarray.ndim 이용

In [7]:
print('array1: {:0}차원, array2:{:1}차원, array3:{:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2:2차원, array3: 2차원


**ndarray의 데이터 타입**

ndarray내의 데이터 값은 숫자 값, 문자열 값, 불 값 등이 모두 가능
숫자형: int(8bit, 16bit, 32bit), float(16bit, 64bit, 128bit), complex 

- 연산: 같은 데이터 타입만 가능, 한 개의 ndarray 객체에 int와 float가 함께 있을 수 없음
- dtype속성으로 데이터 타입 확인 가능

In [8]:
list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [9]:
list2=[1,2,'test']
array2=np.array(list2)
print(array2, array2.dtype)

list3=[1,2,3.0]
array3=np.array(list3)
print(array3, array3.dtype)

# int와 문자열이 섞여 있는 경우 모두 문자열로 변환
# int와 float인 경우 모두 float으로 변환

['1' '2' 'test'] <U21
[1. 2. 3.] float64


**ndarray를 편리하게 생성하기 - arange, zeros, ones**

arange( ): array를 range( )로 표현, 0부터 인자값 -1값까지의 값을 순차적으로 ndarray의 데이터값으로 변환해 줍니다.

In [11]:
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


zeros( ): 튜플 형태의 shape값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 봔환

ones( ): zeros()에서 0대신 1

In [13]:
zero_array=np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


**ndarray의 차원과 크기를 변경하는 reshape( )**

In [14]:
array1=np.arange(10)
print('array1:\n', array1)

array2=array1.reshape(2,5)
print('array2:\n', array2)

array3=array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [15]:
#array1.reshape(4,3)
#오류 확인

ValueError: ignored

In [18]:
# 인자로 -1 사용
array1=np.arange(10)
print(array1)
array2=array1.reshape(-1,5)
print('array2 shape:', array2.shape)
array3=array1.reshape(5,-1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [20]:
array1=np.arange(10)
#array4=array1.reshape(-1,4)
#오류 확인

ValueError: ignored

In [21]:
array1=np.arange(8)
array3d=array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

#3차원 ndarray를 2차원 ndqrray로 변환
array5=array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

#1차원 ndarray를 2차원 ndqrray로 변환
array6=array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


**넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(indexing)**

1. 특정한 데이터만 추출
2. 슬라이싱
3. 팬시 슬라이싱: 리스트 또는 ndarray 형태로 지정해 ndarray를 반환
4. 불린 인덱싱: True에 해당하는 인덱싱 위치에 있는 데이터의 ndarray를 반환

**단일 값 추출**

In [22]:
#1부터 9까지의 1차원 ndarray 생성
array1= np.arange(start=1, stop=10)
print('array1:', array1)

#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value=array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [23]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [24]:
#단일 인덱스로 데이터값 수정 가능
array1[0]=9
array1[8]=0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [26]:
#다차원

array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


**슬라이싱**

: 기호를 이용하여 연속한 데이터 슬라이싱해서 추출

In [28]:
from numpy.core.getlimits import array
array1=np.arange(start=1, stop=10)
array3=array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [29]:
array1=np.arange(start=1, stop=10)
array4=array1[:3]
print(array4)

array5=array1[3:]
print(array5)

array6=array1[:]
print(array6)


[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [31]:
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2]:\n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3]:\n', array2d[1:3, 0:3])
print('array2d[1:3, :]:\n', array2d[1:3, :])
print('array2d[:, :]:\n', array2d[:, :])
print('array2d[:2, 1:]:\n', array2d[:2, 1:])
print('array2d[:2, 0]:\n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]:
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]:
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]:
 [[4 5 6]
 [7 8 9]]
array2d[:, :]:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]:
 [[2 3]
 [5 6]]
array2d[:2, 0]:
 [1 4]


In [32]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


**팬시 인덱싱**

인덱스 집항르 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식

In [33]:
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)

array3=array2d[[0,1],2]
print('array2d[[0,1],2] =>', array3.tolist())

array4=array2d[[0,1],0:2]
print('array2d[[0,1],0:2] =>', array4.tolist())

array5=array2d[[0,1]]
print('array2d[[0,1]] =>', array5.tolist())

array2d[[0,1],2] => [3, 6]
array2d[[0,1],0:2] => [[1, 2], [4, 5]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


**불린 인덱싱**

for loop/if else문보다 훨씬 간단하게 구현 가능

In [35]:
array1d=np.arange(start=1, stop=10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용
array3=array1d[array1d>5]
print('array1d>5 불린 인덱싱 결과 값:', array3)

array1d>5 불린 인덱싱 결과 값: [6 7 8 9]


In [36]:
array1d>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [37]:
boolean_indexes=np.array([False, False, False, False, False,  True,  True,  True,  True])
array3=array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과: ', array3)

불린 인덱스로 필터링 결과:  [6 7 8 9]


In [38]:
indexes=np.array([5,6,7,8])
array4=array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)

일반 인덱스로 필터링 결과: [6 7 8 9]


**행렬의 정렬 - sort( )와 argsort( )**

- 행렬 정렬

In [40]:
org_array=np.array([3, 1, 9, 5])
print('원본 행렬:', org_array)
#np.sort( )로 정렬
sort_array1=np.sort(org_array)
print('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort( ) 호출 후 원본 행렬:', org_array)
#ndarray.sort( )로 정렬
sort_array2=org_array.sort()
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


In [41]:
sort_array1_desc=np.sort(org_array[::-1])
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [1 3 5 9]


In [43]:
array2d=np.array([[8,12],
                  [7,1 ]])
sort_array2d_axis0=np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1=np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


- 정렬된 행렬의 인덱스를 반환하기

In [45]:
org_array=np.array([3, 1, 9, 5])
sort_indices=np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [47]:
org_array=np.array([3, 1, 9, 5])
sort_indices_desc=np.argsort(org_array[::-1])
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [50]:
import numpy as np

name_array=np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array=np.array([78, 95, 84, 98, 88])

sort_indices_asc=np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


**선형대수 연산 - 행렬 내적과 전치 행렬 구하기**

- 행렬 내적(행렬 곱)
: np.dot( ) 이용

In [52]:
A=np.array([[1,2,3],
            [4,5,6]])
B=np.array([[7,8],
            [9,10],
            [11,12]])

dot_product=np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


- 전치 행렬
: transpose( )

In [53]:
A= np.array([[1,2],
             [3,4]])
transpose_mat=np.transpose(A)
print('A의 전치 행렬: \n', transpose_mat)

A의 전치 행렬: 
 [[1 3]
 [2 4]]
